name: VQfMRI
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.8
  - pip=22.1.2
  - cudatoolkit=11.3.1
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy=1.21.5
  - pip:
    - einops==0.3.0
    - pillow==9.2.0